**Intodution** **Numpy** 

In [ ]:
revenus=[1800,1500,2200,3000,2172]

In [ ]:
def Average(lst):
    return sum(lst) / len(lst)

In [ ]:
average = Average(revenus)

In [ ]:
print("Average of the list =", round(average, 2))

Average of the list = 2134.4


In [ ]:
import numpy as np
revenus = np.array([1800,1500,2200,3000,2172])

In [ ]:
revenus.mean()

2134.4

In [8]:
np.argmin(revenus)

1

In [9]:
np.argmax(revenus)

3

In [10]:
np.sort(revenus)

array([1500, 1800, 2172, 2200, 3000])

In [11]:
revenus[:3]

array([1800, 1500, 2200])

In [12]:
revenus[::2]

array([1800, 2200, 2172])

In [13]:
revenus[revenus>2000]

array([2200, 3000, 2172])

In [18]:
tab = np.random.random_integers(1,10,size=(3,3))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """Entry point for launching an IPython kernel.


In [19]:
display(tab)

array([[5, 5, 2],
       [9, 1, 9],
       [6, 4, 3]])

In [20]:
tab[0,:]

array([5, 5, 2])

In [34]:
tt = [1,2,3]
row = np.array([7,8,9])
tab = np.r_[tab,[row]]
print(tab)

[[5 5 2]
 [9 1 9]
 [6 4 3]]
[[5 5 2]
 [9 1 9]
 [6 4 3]
 [7 8 9]]


In [32]:
tab = np.delete(tab,(3), axis=0)
print (tab)

[[5 5 2]
 [9 1 9]
 [6 4 3]]


**Introduction** **Pandas**

In [35]:
import pandas as pd

In [36]:
data = {"state": ["Tunis", "Bizerte", "Sfax",
"Sousse", "Gabes"],
"year": [2000, 2001, 2002, 2001, 2002],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9]}

In [57]:
df = pd.DataFrame(data)

In [40]:
display(df)

state  year  pop
0    Tunis  2000  1.5
1  Bizerte  2001  1.7
2     Sfax  2002  3.6
3   Sousse  2001  2.4
4    Gabes  2002  2.9

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   state   5 non-null      object 
 1   year    5 non-null      int64  
 2   pop     5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes


In [42]:
df.columns

Index(['state', 'year', 'pop'], dtype='object')

In [43]:
df['state']

0      Tunis
1    Bizerte
2       Sfax
3     Sousse
4      Gabes
Name: state, dtype: object

In [45]:
df.state

0      Tunis
1    Bizerte
2       Sfax
3     Sousse
4      Gabes
Name: state, dtype: object

In [48]:
df.pop=1.5

In [58]:
df["zone"]="Nord"

In [47]:
display(df)

state  year  pop  zone
0    Tunis  2000  1.5  Nord
1  Bizerte  2001  1.7  Nord
2     Sfax  2002  3.6  Nord
3   Sousse  2001  2.4  Nord
4    Gabes  2002  2.9  Nord

In [59]:
df = df.rename(columns={
    'state': 's',
    'year':'y',
    'pop': 'p',
    'zone':'z'}
)
df.columns

Index(['s', 'y', 'p', 'z'], dtype='object')

In [61]:
del df["p"]

In [62]:
df.columns

Index(['s', 'y', 'z'], dtype='object')